SELECT *FROM DEPOSITE
SELECT *FROM BORROW

UPDATE DEPOSITE SET AMOUNT = 5000 
WHERE AMOUNT=3000

UPDATE BORROW SET BNAME='C.G.ROAD'
WHERE CNAME = 'ANIL'

UPDATE DEPOSITE SET ACTNO=111 , AMOUNT=5000
where CNAME = 'SANDIP'

UPDATE BORROW SET AMOUNT = AMOUNT+(AMOUNT/10)

UPDATE DEPOSITE SET AMOUNT=5000
WHERE ACTNO BETWEEN 103 AND 107

UPDATE BORROW SET AMOUNT=NULL
WHERE LOANNO=321

SELECT LOANNO FROM BORROW 
WHERE AMOUNT=NULL

