--1. Find out the square root of 36, 49 and 81.

	SELECT SQRT(36),SQRT(49),SQRT(81)

--2. Find out the square of 3, 9, and 12. 

SELECT SQUARE(3),SQUARE(9),SQUARE(12)

--3. Find out round value of 280.8952 for 2, 0 and -2 decimal points.
	SELECT ROUND(280.8952,2), ROUND(280.8952,0), ROUND(280.8952,-2)

--4. Find sine, cosine and tangent of 4.2014. 
SELECT SIN(4.2014),COS(4.2014),TAN(4.2014)


--5. Find sign of -55, 0 and 95.
SELECT SIGN(-55),SIGN(0),SIGN(95)